### PR TITLE
get testthat tests to pass with devtools::check()

### PR DESCRIPTION
**Pull request by alexkyllo**
#20

### CODE REVIEW

**Comment by alexkyllo** [comment]
Now the only error I get from `devtools::check()` is:

```
Error in grDevices::pdf(paste(pkgname, "-Ex.pdf", sep = ""), encoding = "ISOLatin1") : 
  cannot open file 'AzureKusto-Ex.pdf'
```

Not sure what this means or how to fix it. Is this something I need to worry about?

**Comment by Hong-Revo** [comment]
I still get the following on running check():

```
* checking S3 generic/method consistency ... WARNING
Warning: declared S3 method 'filter.tbl_kusto_abstract' not found
Warning: declared S3 method 'intersect.tbl_kusto_abstract' not found
Warning: declared S3 method 'setdiff.tbl_kusto_abstract' not found
Warning: declared S3 method 'setequal.tbl_kusto_abstract' not found
Warning: declared S3 method 'union.tbl_kusto_abstract' not found
kql_render:
  function(query, ...)
kql_render.kql_query:
  function(query)

print:
  function(x, ...)
print.kql:
  function(x)

head:
  function(x, ...)
head.tbl_kusto_abstract:
  function(.data, n, ...)
```

Note that the first argument for a method must match with that of the generic, eg `head.tbl_kusto_abstract` should have signature `(x, n, ...)`; and if the generic has a `...` argument, the methods must have it too. I'm not sure why check() complains about the missing methods though.

You're probably getting the pdf error because you don't have Latex installed; R CMD check saves the outputs from the examples in a pdf file and the pdf creation tool is part of Latex. I think. I wouldn't worry about it right now.

**Comment by Hong-Revo** [comment]
I'd also suggest installing the rhub package and using the `check_for_cran` function from that. Unfortunately the R-Hub backend is glitching out at the moment....

**Comment by Hong-Revo** [comment]
Sweet. I just removed the `@importFrom` since we already import all of dplyr.

**Pull request merged**
