### PR TITLE
Escape identifiers with [' ']

### PR DESCRIPTION
**Pull request by Hong-Revo**
Uncovered possible bugs: #32, #33

### CODE REVIEW

**Comment by Hong-Revo** [comment]
See also #36

**Comment by Hong-Revo** [comment]
@alexkyllo This should be good to review.

- Fixes the bugs noted above
- Adds a print method; this just prints either the table name or the rendered query
- Changed `simulate_kusto` to have a `server` component rather than `cluster`, to match the actual database endpoint structure
- Made `simulate_kusto` the default src argument for `tbl_kusto_abstract`; I don't see a reason to keep the NULL default (in fact, the src argument could be done away with entirely).

**Comment by alexkyllo** [comment]
I got kinda busy with other work this week, but I'll try and get this reviewed today.

**Comment by alexkyllo** [comment]
The last example in the README fails. The identifier escaping with [' '] wraps around the arguments.

```r
> MyFunctionDate <- tbl_kusto(Samples, "MyFunctionDate(dt)", dt=as.Date("2019-01-01"))
Error in call_kusto(uri, body, auth_str, http_status_handler = .http_status_handler) : 
  Bad Request (HTTP 400). Failed to complete Kusto operation. Message:
Request is invalid and cannot be executed.
Semantic error: 'declare query_parameters (dt:datetime) ; ['MyFunctionDate(dt)'] | take 1' 
has the following semantic error: 
SEM0100: 'take' operator: 
Failed to resolve table or column expression named '["MyFunctionDate(dt)"]'.
```

Instead of generating `['MyFunctionDate(dt)']` it needs to generate `['MyFunctionDate'](dt)`

We also should have a unit test that catches this.

**Comment by Hong-Revo** [comment]
gonna merge this now; still need to add a test for a parameterized table expression but that can happen later.

**Pull request merged**
