### PR TITLE
Refactoring query endpoint interface

### PR DESCRIPTION
**Pull request by Hong-Revo**

### CODE REVIEW

**Comment by Hong-Revo** [comment]
I added basicauth support before I learned that it's disabled. I don't think it'll hurt to leave it in; it doesn't affect anything else.

**Comment by Hong-Revo** [comment]
I'll be adding tests Real Soon Now

**Comment by alexkyllo** [comment]
Just let me know when you're ready for me to take another look over it and merge it. I was hoping to test out your code manually at least, but the issue I'm having getting a token with AzureRMR might block me from doing that for the time being.

**Comment by Hong-Revo** [comment]
I'll go ahead and commit this, so it doesn't hold up the next thing: renaming objects from the `ade/data_explorer` naming scheme to `kusto`.

**Pull request merged**
